#!/bin/bash

#PBS -j oe 
#PBS -o lbm.out
#PBS -q teaching
#PBS -l nodes=1:ppn=16,walltime=01:00:00

# Change the working directory (default is home directory)
cd "$PBS_O_WORKDIR"
  
echo "Running on host: $(hostname)"
echo "Time is: $(date)"
echo "Directory is: $(pwd)"
echo "PBS job ID is: $PBS_JOBID"
echo "This jobs runs on the following machines: $(cat "$PBS_NODEFILE" | uniq)"
echo
module load languages/intel-compiler-16-u2
module load languages/python-2.7.6
source ~/intel/vtune_amplifier_2019.2.0.588069/amplxe-vars.sh

# Run the executable
echo "128 x 128"
echo "----------------------------------"
#amplxe-cl -quiet -collect hotspots -result-dir s01-128 ./lbm input_128x128.params obstacles_128x128.dat
./lbm input_128x128.params obstacles_128x128.dat
echo "----------------------------------"
echo
make check-small
echo
echo "256 x 256"
echo "----------------------------------"
./lbm input_256x256.params obstacles_256x256.dat
echo "----------------------------------"
echo
make check-medium
echo
echo "1024 x 1024"
echo "----------------------------------"
./lbm input_1024x1024.params obstacles_1024x1024.dat
echo "----------------------------------"
echo
make check-large
echo

